import { useId } from "react";

/**
 * The Kaldera mark (brand Direction 3): a caldera from above — cooled crust
 * fractured into plates, the eastern arc still molten.
 *
 * GENERATED by scripts/build-brand.mjs from scripts/brand-mark.mjs. Edit the
 * geometry there and re-run, or the favicon and touch icon will drift out of
 * step with what the page shows.
 */
export function KalderaMark({
  className,
  title,
}: {
  className?: string;
  title?: string;
}) {
  // The crack mask is a document-scoped id — nav and footer both render one.
  // useId() bakes colons into the value, which some engines choke on inside a
  // url(#…) fragment reference; strip them.
  const id = `kaldera-crust-${useId().replace(/:/g, "")}`;
  return (
    <svg
      viewBox="0 0 64 64"
      className={className}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : true}
      focusable="false"
    >
      {title && <title>{title}</title>}
      <defs>
        <mask id={id}>
          <circle cx="32" cy="32" r="24" fill="#fff" />
          <circle cx="32" cy="32" r="13" fill="#000" />
          <polyline
            points="36.72,22.73 38.39,19.77 39.00,16.95 42.54,15.71 43.25,12.86 41.50,8.66 44.44,7.59"
            stroke="#000"
            strokeWidth={2.3}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
          <polyline
            points="42.09,34.52 45.48,34.98 48.38,34.68 51.12,35.27 53.26,38.40 56.82,36.36 58.59,38.63"
            stroke="#000"
            strokeWidth={2.3}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
          <polyline
            points="37.66,40.72 40.24,43.07 39.63,46.74 42.99,47.99 43.41,51.04 46.89,52.33 46.92,54.98"
            stroke="#000"
            strokeWidth={2.3}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
          <polyline
            points="30.37,42.27 31.23,45.78 28.56,48.24 28.54,51.09 28.01,53.84 29.10,57.03 27.71,59.06"
            stroke="#000"
            strokeWidth={2.3}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
          <polyline
            points="23.69,38.26 20.29,39.30 18.69,41.92 15.71,42.54 14.12,45.16 12.30,47.71 10.12,48.49"
            stroke="#000"
            strokeWidth={2.3}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
          <polyline
            points="21.79,30.02 18.61,28.68 15.59,29.50 12.67,30.35 10.20,27.78 7.20,27.51 5.10,26.77"
            stroke="#000"
            strokeWidth={2.3}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
          <polyline
            points="27.77,22.50 26.56,19.32 23.95,17.48 23.09,14.77 22.71,11.84 21.78,8.96 20.86,6.97"
            stroke="#000"
            strokeWidth={2.3}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />
        </mask>
      </defs>
      <g mask={`url(#${id})`}>
        <circle cx="32" cy="32" r="24" fill="currentColor" />
        <path d="M42.90 10.62A24 24 0 0 1 45.07 52.13L39.08 42.90A13 13 0 0 0 37.90 20.42Z" fill="var(--color-ember)" />
      </g>
    </svg>
  );
}
