/**
 * Generates every baked brand surface from `brand-mark.mjs`:
 *
 *   public/favicon.svg              — the tab mark
 *   public/og/kaldera-touch.png     — iOS home-screen icon (180×180)
 *   src/components/site/KalderaMark.tsx — the inline mark used in the shell
 *
 * Run with `node scripts/build-brand.mjs` after touching the geometry. The PNG
 * is rasterised here rather than by a dependency: the mark is circles and
 * polylines, which is a distance-field away from being pixels, and adding a
 * native image toolchain to a site with three raster assets is not a trade
 * worth making.
 */

import { deflateSync } from "node:zlib";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BOX,
  CRACKS,
  CRACK_HALF,
  CX,
  CY,
  EMBER,
  OBSIDIAN,
  PUMICE,
  R_IN,
  R_OUT,
  crackPolylineAttr,
  emberWedgePath,
  isEmber,
} from "./brand-mark.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const write = (rel, data) => {
  const out = resolve(root, rel);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, data);
  console.log(`wrote ${rel}`);
};

// ── Shared SVG body ──────────────────────────────────────────────────────
// The cracks are cut with a mask rather than painted in the page colour, so
// the mark stays honest on any ground (the nav, a light OG card, a sticker).

const crackStrokes = CRACKS.map(
  (pts) =>
    `      <polyline points="${crackPolylineAttr(pts)}" stroke="#000" stroke-width="${
      CRACK_HALF * 2
    }" stroke-linecap="round" stroke-linejoin="round" fill="none"/>`,
).join("\n");

function markBody(idSuffix) {
  const id = `kaldera-crust-${idSuffix}`;
  return `  <defs>
    <mask id="${id}">
      <circle cx="${CX}" cy="${CY}" r="${R_OUT}" fill="#fff"/>
      <circle cx="${CX}" cy="${CY}" r="${R_IN}" fill="#000"/>
${crackStrokes}
    </mask>
  </defs>
  <g mask="url(#${id})">
    <circle cx="${CX}" cy="${CY}" r="${R_OUT}" fill="${PUMICE}"/>
    <path d="${emberWedgePath()}" fill="${EMBER}"/>
  </g>`;
}

// ── favicon.svg ──────────────────────────────────────────────────────────
// Kept on its obsidian tile: browsers draw favicons against whatever the tab
// strip happens to be, and a transparent pumice ring vanishes on light chrome.

write(
  "public/favicon.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${BOX} ${BOX}">
  <!-- Kaldera mark: fractured crust, one arc still molten. Generated by
       scripts/build-brand.mjs — edit scripts/brand-mark.mjs, not this file. -->
  <rect width="${BOX}" height="${BOX}" fill="${OBSIDIAN}"/>
${markBody("fav")}
</svg>
`,
);

// ── og/mark.svg ──────────────────────────────────────────────────────────
// Groundless copy of the mark, for the share card and anywhere else the mark
// has to sit on art rather than on a tile.

write(
  "public/og/mark.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${BOX} ${BOX}">
  <!-- Generated by scripts/build-brand.mjs. -->
${markBody("og")}
</svg>
`,
);

// ── KalderaMark.tsx ──────────────────────────────────────────────────────
// `title` is optional: the nav pairs the mark with the wordmark, so there it
// is decorative and must not be announced twice.

write(
  "src/components/site/KalderaMark.tsx",
  `import { useId } from "react";

/**
 * The Kaldera mark (brand Direction 3): a caldera from above — cooled crust
 * fractured into plates, the eastern arc still molten.
 *
 * GENERATED by scripts/build-brand.mjs from scripts/brand-mark.mjs. Edit the
 * geometry there and re-run, or the favicon and touch icon will drift out of
 * step with what the page shows.
 */
export function KalderaMark({
  className,
  title,
}: {
  className?: string;
  title?: string;
}) {
  // The crack mask is a document-scoped id — nav and footer both render one.
  // useId() bakes colons into the value, which some engines choke on inside a
  // url(#…) fragment reference; strip them.
  const id = \`kaldera-crust-\${useId().replace(/:/g, "")}\`;
  return (
    <svg
      viewBox="0 0 ${BOX} ${BOX}"
      className={className}
      role={title ? "img" : undefined}
      aria-hidden={title ? undefined : true}
      focusable="false"
    >
      {title && <title>{title}</title>}
      <defs>
        <mask id={id}>
          <circle cx="${CX}" cy="${CY}" r="${R_OUT}" fill="#fff" />
          <circle cx="${CX}" cy="${CY}" r="${R_IN}" fill="#000" />
${CRACKS.map(
  (pts) =>
    `          <polyline
            points="${crackPolylineAttr(pts)}"
            stroke="#000"
            strokeWidth={${CRACK_HALF * 2}}
            strokeLinecap="round"
            strokeLinejoin="round"
            fill="none"
          />`,
).join("\n")}
        </mask>
      </defs>
      <g mask={\`url(#\${id})\`}>
        <circle cx="${CX}" cy="${CY}" r="${R_OUT}" fill="currentColor" />
        <path d="${emberWedgePath()}" fill="var(--color-ember)" />
      </g>
    </svg>
  );
}
`,
);

// ── kaldera-touch.png ────────────────────────────────────────────────────

const hex = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16));
const GROUND = hex(OBSIDIAN);
const CRUST = hex(PUMICE);
const MOLTEN = hex(EMBER);

/** Squared distance from p to segment ab — the crack test, done cheaply. */
function segDistSq(px, py, ax, ay, bx, by) {
  const dx = bx - ax;
  const dy = by - ay;
  const len = dx * dx + dy * dy;
  let t = len ? ((px - ax) * dx + (py - ay) * dy) / len : 0;
  t = t < 0 ? 0 : t > 1 ? 1 : t;
  const qx = ax + t * dx - px;
  const qy = ay + t * dy - py;
  return qx * qx + qy * qy;
}

function renderPng(size, pad) {
  const SS = 4; // supersample: the mark is all curves, aliasing shows badly
  const scale = (size - pad * 2) / BOX;
  const crackHalfSq = CRACK_HALF * CRACK_HALF;
  // Row-major RGB, one filter byte per scanline (PNG filter type 0).
  const raw = Buffer.alloc(size * (1 + size * 3));

  for (let y = 0; y < size; y++) {
    const row = y * (1 + size * 3);
    raw[row] = 0;
    for (let x = 0; x < size; x++) {
      let hits = 0;
      let emberHits = 0;
      for (let sy = 0; sy < SS; sy++) {
        for (let sx = 0; sx < SS; sx++) {
          // Sample centre → mark space.
          const mx = (x + (sx + 0.5) / SS - pad) / scale;
          const my = (y + (sy + 0.5) / SS - pad) / scale;
          const dx = mx - CX;
          const dy = my - CY;
          const d = Math.hypot(dx, dy);
          if (d < R_IN || d > R_OUT) continue;
          let cracked = false;
          for (const pts of CRACKS) {
            for (let i = 1; i < pts.length && !cracked; i++) {
              const [ax, ay] = pts[i - 1];
              const [bx, by] = pts[i];
              if (segDistSq(mx, my, ax, ay, bx, by) <= crackHalfSq) cracked = true;
            }
            if (cracked) break;
          }
          if (cracked) continue;
          hits++;
          if (isEmber((Math.atan2(dy, dx) * 180) / Math.PI)) emberHits++;
        }
      }
      const total = SS * SS;
      const cover = hits / total;
      const p = row + 1 + x * 3;
      if (!cover) {
        raw[p] = GROUND[0];
        raw[p + 1] = GROUND[1];
        raw[p + 2] = GROUND[2];
        continue;
      }
      // Two colours inside one pixel at the crust/molten seam: mix by share.
      const emberShare = emberHits / hits;
      for (let c = 0; c < 3; c++) {
        const mark = CRUST[c] * (1 - emberShare) + MOLTEN[c] * emberShare;
        raw[p + c] = Math.round(GROUND[c] * (1 - cover) + mark * cover);
      }
    }
  }

  const chunk = (type, body) => {
    const len = Buffer.alloc(4);
    len.writeUInt32BE(body.length);
    const tagged = Buffer.concat([Buffer.from(type, "ascii"), body]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(crc32(tagged) >>> 0);
    return Buffer.concat([len, tagged, crc]);
  };

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 2; // truecolour
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", deflateSync(raw, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

const CRC_TABLE = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return c ^ -1;
}

// iOS crops the corners of the touch icon, so the ring gets real margin.
write("public/og/kaldera-touch.png", renderPng(180, 22));
