/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ZoologicRouteImport } from './routes/zoologic'
import { Route as ProtoCalderaRouteImport } from './routes/proto.caldera'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsAureaRouteImport } from './routes/tools.aurea'
import { Route as ToolsCinevidoRouteImport } from './routes/tools.cinevido'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoologicRoute = ZoologicRouteImport.update({
  id: '/zoologic',
  path: '/zoologic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoCalderaRoute = ProtoCalderaRouteImport.update({
  id: '/proto/caldera',
  path: '/proto/caldera',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAureaRoute = ToolsAureaRouteImport.update({
  id: '/tools/aurea',
  path: '/tools/aurea',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCinevidoRoute = ToolsCinevidoRouteImport.update({
  id: '/tools/cinevido',
  path: '/tools/cinevido',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/zoologic': typeof ZoologicRoute
  '/proto/caldera': typeof ProtoCalderaRoute
  '/tools/aurea': typeof ToolsAureaRoute
  '/tools/cinevido': typeof ToolsCinevidoRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/zoologic': typeof ZoologicRoute
  '/proto/caldera': typeof ProtoCalderaRoute
  '/tools/aurea': typeof ToolsAureaRoute
  '/tools/cinevido': typeof ToolsCinevidoRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop': typeof ShopRoute
  '/studio': typeof StudioRoute
  '/zoologic': typeof ZoologicRoute
  '/proto/caldera': typeof ProtoCalderaRoute
  '/tools/aurea': typeof ToolsAureaRoute
  '/tools/cinevido': typeof ToolsCinevidoRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shop'
    | '/studio'
    | '/zoologic'
    | '/proto/caldera'
    | '/tools/aurea'
    | '/tools/cinevido'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shop'
    | '/studio'
    | '/zoologic'
    | '/proto/caldera'
    | '/tools/aurea'
    | '/tools/cinevido'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/shop'
    | '/studio'
    | '/zoologic'
    | '/proto/caldera'
    | '/tools/aurea'
    | '/tools/cinevido'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopRoute: typeof ShopRoute
  StudioRoute: typeof StudioRoute
  ZoologicRoute: typeof ZoologicRoute
  ProtoCalderaRoute: typeof ProtoCalderaRoute
  ToolsAureaRoute: typeof ToolsAureaRoute
  ToolsCinevidoRoute: typeof ToolsCinevidoRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoologic': {
      id: '/zoologic'
      path: '/zoologic'
      fullPath: '/zoologic'
      preLoaderRoute: typeof ZoologicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/caldera': {
      id: '/proto/caldera'
      path: '/proto/caldera'
      fullPath: '/proto/caldera'
      preLoaderRoute: typeof ProtoCalderaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/aurea': {
      id: '/tools/aurea'
      path: '/tools/aurea'
      fullPath: '/tools/aurea'
      preLoaderRoute: typeof ToolsAureaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cinevido': {
      id: '/tools/cinevido'
      path: '/tools/cinevido'
      fullPath: '/tools/cinevido'
      preLoaderRoute: typeof ToolsCinevidoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopRoute: ShopRoute,
  StudioRoute: StudioRoute,
  ZoologicRoute: ZoologicRoute,
  ProtoCalderaRoute: ProtoCalderaRoute,
  ToolsAureaRoute: ToolsAureaRoute,
  ToolsCinevidoRoute: ToolsCinevidoRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
